apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120  # Wait 120s before scaling down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60            # Remove at most 1 pod per minute
    scaleUp:
      stabilizationWindowSeconds: 60   # Wait 60s before scaling up
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60            # Add at most 2 pods per minute