apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: nl-to-sql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/chatwithdata-451800/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        env:
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GCP_PROJECT_ID
