apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-app-backend
  template:
    metadata:
      labels:
        app: llm-app-backend
    spec:
      containers:
      - name: backend
        image: gcr.io/chatwithdata-451800/chatwithdatabase-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "True"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: llm-app-backend
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP