apiVersion: v1
kind: Secret
metadata:
  name: app-secrets  # This is the actual name of the secret
  namespace: nl-to-sql
type: Opaque
data:
  GCP_PROJECT_ID: Y2hhdHdpdGhkYXRhLTQ1MTgwMA==  # Base64 encoded value of "chatwithdata-451800"
