name: Deploy to GCP
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Authenticate to GCP
        run: echo "$GOOGLE_CREDENTIALS" > creds.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Deploy to Cloud Run
        run: gcloud run deploy llm-chatbot --source .
